//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minkin_Lab02.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Minkin_Lab02.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Cant copy {0}!.
        /// </summary>
        public static string CopyFileError {
            get {
                return ResourceManager.GetString("CopyFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Cant create &quot;{0}&quot; folder!.
        /// </summary>
        public static string CreateFolderError {
            get {
                return ResourceManager.GetString("CreateFolderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong format.
        /// </summary>
        public static string DateFormatError {
            get {
                return ResourceManager.GetString("DateFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Cant delete {0}!.
        /// </summary>
        public static string DeleteFileError {
            get {
                return ResourceManager.GetString("DeleteFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to exit.
        /// </summary>
        public static string PressAnyKey {
            get {
                return ResourceManager.GetString("PressAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Cant read config!.
        /// </summary>
        public static string ReadConfigError {
            get {
                return ResourceManager.GetString("ReadConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Cant read log!.
        /// </summary>
        public static string ReadLogError {
            get {
                return ResourceManager.GetString("ReadLogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset folder condition. Enter date and time (for example DD/MM/YYYY HH:MM:SS) or empty string, if you want return current condition:.
        /// </summary>
        public static string ResetText {
            get {
                return ResourceManager.GetString("ResetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select mode:{0}   1:Watch {0}   2:Reset.
        /// </summary>
        public static string SelectModeText {
            get {
                return ResourceManager.GetString("SelectModeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something goes wrong!.
        /// </summary>
        public static string UndefinedError {
            get {
                return ResourceManager.GetString("UndefinedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Cant write config!.
        /// </summary>
        public static string WriteConfigError {
            get {
                return ResourceManager.GetString("WriteConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Cant write log!.
        /// </summary>
        public static string WriteLogError {
            get {
                return ResourceManager.GetString("WriteLogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Wrong mode!.
        /// </summary>
        public static string WrongMode {
            get {
                return ResourceManager.GetString("WrongMode", resourceCulture);
            }
        }
    }
}
